version: "3"

networks: 
  qiita:
    external:
      name: qiita

############
# 基盤
############
services:
  qiita_php:
    build:
      context: ./docker/php
      args:
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        - XDEBUG_REMOTE_CONNECT_BACK=${XDEBUG_REMOTE_CONNECT_BACK}
    container_name: "qiita_php"
    volumes:
      - ${SRC_DIR}:/var/www/qiita/:z
      - ./logs/php/:/var/log/php/error.log
      - ./mnt:/mnt
    environment:
      - TZ="Asia/Tokyo"
    tty: true
    command: >
        bash -c "php-fpm"
    depends_on:
      - mysql
    networks: 
      - qiita

  qiita_nginx:
    build: 
      context: ./docker/nginx
      args:
        - VIRTUAL_HOST=${VIRTUAL_HOST}
    container_name: "qiita_nginx"
    hostname: "qiita_nginx"
    depends_on:
      - qiita_php
    links:
      - qiita_php:php
    ports:
      - ${WEB_PORT}:90
    volumes:
      - ${SRC_DIR}:/var/www/qiita:z
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ="Asia/Tokyo"
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks: 
      - qiita

  mysql:
    image: mysql:5.7
    container_name: "qiita_db"
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - "TZ=Asia/Tokyo"
    ports:
      - ${DB_PORT}:3306
    networks: 
      - qiita

  qiita_batch:
    container_name: "qiita_batch"
    build: 
      context: ./docker/python
    tty: true
    volumes:
      - ./batch:/usr/src/app
      - ./mnt:/mnt
    networks:
      - qiita